### ISSUE TITLE
GPG plugin fails to upload to Sonatype

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/jenkins-jobs#3]
We have 16 nodes, but only a certain number of nodes have issues with the GPG plugin, and the upload fails.

We recently had this issue when releasing the Kinesis binder.

**Comment by trevormarshall** [comment]
Might be a gnupg v1 vs v2 issue. Point me to failures and passes, hopefully I can confirm.

**Comment by sabbyanandan** [comment]
Thanks, Trevor! @sobychacko: It's all you, sir ..

**Comment by sobychacko** [comment]
Hi @trevormarshall here is a sample failure output: https://jenkins.spring.io/job/spring-cloud-stream-binder-aws-kinesis-master-ci/511/console

**Comment by trevormarshall** [comment]
The Jenkins cluster slaves have all been updated to correct the errors. Please re-open if the issue persists.
